version: 2.1

commands:
  checkout-code:
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: git submodule update --init --recursive

jobs:
  tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout-code
      - run:
          name: Dependencies
          command: |
            rm -rf node_modules/
            sudo -H npm install -g truffle@5.1.46 typescript
            yarn install --pure-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - run:
          name: Coverage
          command: truffle run coverage
      - run:
          name: Upload coverage
          command: bash <(curl -s https://codecov.io/bash) || true
  linting:
    docker:
      - image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout-code
      - run:
          name: Dependencies
          command: |
            sudo apt-get install -y python3-setuptools python3-pip
            sudo -H pip3 install slither-analyzer
            sudo -H npm install -g solhint
      - run:
          name: Solhint
          command: solhint "contracts/**/*.sol"
      - run:
          name: Slither
          command: slither --exclude solc-version,timestamp,boolean-equality,unimplemented-functions,locked-ether --solc-version 0.7.4 --filter-paths vendor/ .            

workflows:
  build:
    jobs:
      - tests
      - linting